spring:
  application:
    name: service-vod
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
server:
  port: 8002
